import 'package:json_annotation/json_annotation.dart';

part 'client_event.g.dart';

/// Represents an event generated by the client, not yet acknowledged by the server.
@JsonSerializable()
class ClientEvent {
  /// Client-generated unique event ID (UUID recommended).
  final String clientEventId;

  /// Domain event type name.
  final String type;

  /// Arbitrary JSON content describing the mutation.
  final Map<String, dynamic> payload;

  /// The time the event was created, in milliseconds since epoch.
  final int timestamp;

  ClientEvent({
    required this.clientEventId,
    required this.type,
    required this.payload,
    int? timestamp,
  }) : timestamp = timestamp ?? DateTime.now().millisecondsSinceEpoch;

  /// Creates a new `ClientEvent` from a JSON map.
  factory ClientEvent.fromJson(Map<String, dynamic> json) =>
      _$ClientEventFromJson(json);

  /// Converts this `ClientEvent` to a JSON map.
  Map<String, dynamic> toJson() => _$ClientEventToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientEvent &&
          runtimeType == other.runtimeType &&
          clientEventId == other.clientEventId;

  @override
  int get hashCode => clientEventId.hashCode;
}