// Mocks generated by Mockito 5.4.6 from annotations
// in nagada_client/test/sync_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nagada_client/core/models/client_event.dart' as _i8;
import 'package:nagada_client/core/models/sync_request.dart' as _i5;
import 'package:nagada_client/core/models/sync_response.dart' as _i2;
import 'package:nagada_client/protocol/http_sync_transport.dart' as _i3;
import 'package:nagada_client/storage/offset_store.dart' as _i6;
import 'package:nagada_client/storage/pending_outbox.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResponse_0 extends _i1.SmartFake implements _i2.SyncResponse {
  _FakeSyncResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpSyncTransport].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpSyncTransport extends _i1.Mock implements _i3.HttpSyncTransport {
  MockHttpSyncTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SyncResponse> sync(_i5.SyncRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#sync, [request]),
            returnValue: _i4.Future<_i2.SyncResponse>.value(
              _FakeSyncResponse_0(this, Invocation.method(#sync, [request])),
            ),
          )
          as _i4.Future<_i2.SyncResponse>);
}

/// A class which mocks [OffsetStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffsetStore extends _i1.Mock implements _i6.OffsetStore {
  MockOffsetStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<void> save(int? offset) =>
      (super.noSuchMethod(
            Invocation.method(#save, [offset]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PendingOutbox].
///
/// See the documentation for Mockito's code generation for more information.
class MockPendingOutbox extends _i1.Mock implements _i7.PendingOutbox {
  MockPendingOutbox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> add(_i8.ClientEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#add, [event]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.ClientEvent>> pending() =>
      (super.noSuchMethod(
            Invocation.method(#pending, []),
            returnValue: _i4.Future<List<_i8.ClientEvent>>.value(
              <_i8.ClientEvent>[],
            ),
          )
          as _i4.Future<List<_i8.ClientEvent>>);

  @override
  _i4.Future<void> markAsSynced(List<String>? clientEventIds) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [clientEventIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
